name: Debugging with SSH
on:
  workflow_dispatch:
    inputs:
      Debug with SSH:
        description: 'SSH?'
        required: true
        default: 'Of course!'
jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 16

    - name: SSH
      uses: mxschmitt/action-tmate@v3
